create table chat_messages (id bigint not null auto_increment, content varchar(255), content_type varchar(255), date datetime(6), sender_id varchar(255), sender_name varchar(255), primary key (id)) engine=InnoDB;
create table events (id bigint not null auto_increment, capacity integer, event_banner varchar(255), event_date_time varchar(255), event_details varchar(255), event_location varchar(255), event_name varchar(255), event_status integer, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table leases (id bigint not null, lease_end_date date, lease_id bigint, lease_length integer, lease_start_date date, lease_status varchar(255), unit_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table maintenance_requests (id bigint not null, img varchar(255), request_date date, request_description varchar(255), request_id bigint, request_status varchar(255), unit_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table residences (id bigint not null, address varchar(255), description varchar(255), name varchar(255), residence_id bigint, manager_id bigint, primary key (id)) engine=InnoDB;
create table roommate_profile (id bigint not null auto_increment, contact_method varchar(255), description varchar(255), drinking integer not null, hobbies varchar(255), pets integer not null, smoking integer not null, user_id bigint not null, primary key (id)) engine=InnoDB;
create table rsvp (id bigint not null auto_increment, event_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table units (id bigint not null, monthly_rent decimal(19,2), unit_description varchar(255), unit_id bigint, unit_number varchar(255), unit_type varchar(255), residence_id bigint, primary key (id)) engine=InnoDB;
create table users (id bigint not null, address varchar(255), college_name varchar(255), date_of_birth date, email varchar(255), fcm varchar(255), first_name varchar(255), img varchar(255), last_name varchar(255), password varchar(255), phone_number varchar(255), postal_code varchar(255), role integer, student_id varchar(255), primary key (id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table roommate_profile add constraint UK_4apvk7j5x1e71vrap7ldeno0v unique (user_id);
alter table leases add constraint FK5noeykhrutapru4f8jnx75sm4 foreign key (unit_id) references units (id);
alter table leases add constraint FKvpstuvbfjau91d62sor5a321 foreign key (user_id) references users (id);
alter table maintenance_requests add constraint FKg0yit7sqjjsyy3vftm7tkkhq3 foreign key (unit_id) references units (id);
alter table maintenance_requests add constraint FKo9pxh9quq4cihxotf6qyw9gpd foreign key (user_id) references users (id);
alter table residences add constraint FKi4u7wp3anfvtl9moqurlncur7 foreign key (manager_id) references users (id);
alter table roommate_profile add constraint FKcruip685m7g5ow3ukirl3uerc foreign key (user_id) references users (id);
alter table rsvp add constraint FK1w4gusckkqul6iyf6r0teov88 foreign key (event_id) references events (id);
alter table rsvp add constraint FKku8yxwk1j6g9muxm7c2f1dmwv foreign key (user_id) references users (id);
alter table units add constraint FK70p695jgs0dhdv5ldf5i1puta foreign key (residence_id) references residences (id);
create table chat_messages (id bigint not null auto_increment, content varchar(255), content_type varchar(255), date datetime(6), sender_id varchar(255), sender_name varchar(255), primary key (id)) engine=InnoDB;
create table events (id bigint not null auto_increment, capacity integer, event_banner varchar(255), event_date_time varchar(255), event_details varchar(255), event_location varchar(255), event_name varchar(255), event_status integer, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table leases (id bigint not null, lease_end_date date, lease_id bigint, lease_length integer, lease_start_date date, lease_status varchar(255), unit_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table maintenance_requests (id bigint not null, img varchar(255), request_date date, request_description varchar(255), request_id bigint, request_status varchar(255), unit_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table residences (id bigint not null, address varchar(255), description varchar(255), name varchar(255), residence_id bigint, manager_id bigint, primary key (id)) engine=InnoDB;
create table roommate_profile (id bigint not null auto_increment, contact_method varchar(255), description varchar(255), drinking integer not null, hobbies varchar(255), pets integer not null, smoking integer not null, user_id bigint not null, primary key (id)) engine=InnoDB;
create table rsvp (id bigint not null auto_increment, event_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table units (id bigint not null, monthly_rent decimal(19,2), unit_description varchar(255), unit_id bigint, unit_number varchar(255), unit_type varchar(255), residence_id bigint, primary key (id)) engine=InnoDB;
create table users (id bigint not null, address varchar(255), college_name varchar(255), date_of_birth date, email varchar(255), fcm varchar(255), first_name varchar(255), img varchar(255), last_name varchar(255), password varchar(255), phone_number varchar(255), postal_code varchar(255), role integer, student_id varchar(255), primary key (id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table roommate_profile add constraint UK_4apvk7j5x1e71vrap7ldeno0v unique (user_id);
alter table leases add constraint FK5noeykhrutapru4f8jnx75sm4 foreign key (unit_id) references units (id);
alter table leases add constraint FKvpstuvbfjau91d62sor5a321 foreign key (user_id) references users (id);
alter table maintenance_requests add constraint FKg0yit7sqjjsyy3vftm7tkkhq3 foreign key (unit_id) references units (id);
alter table maintenance_requests add constraint FKo9pxh9quq4cihxotf6qyw9gpd foreign key (user_id) references users (id);
alter table residences add constraint FKi4u7wp3anfvtl9moqurlncur7 foreign key (manager_id) references users (id);
alter table roommate_profile add constraint FKcruip685m7g5ow3ukirl3uerc foreign key (user_id) references users (id);
alter table rsvp add constraint FK1w4gusckkqul6iyf6r0teov88 foreign key (event_id) references events (id);
alter table rsvp add constraint FKku8yxwk1j6g9muxm7c2f1dmwv foreign key (user_id) references users (id);
alter table units add constraint FK70p695jgs0dhdv5ldf5i1puta foreign key (residence_id) references residences (id);
create table chat_messages (id bigint not null auto_increment, content varchar(255), content_type varchar(255), date datetime(6), sender_id varchar(255), sender_name varchar(255), primary key (id)) engine=InnoDB;
create table events (id bigint not null auto_increment, capacity integer, event_banner varchar(255), event_date_time varchar(255), event_details varchar(255), event_location varchar(255), event_name varchar(255), event_status integer, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table leases (id bigint not null, lease_end_date date, lease_id bigint, lease_length integer, lease_start_date date, lease_status varchar(255), unit_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table maintenance_requests (id bigint not null, img varchar(255), request_date date, request_description varchar(255), request_id bigint, request_status varchar(255), unit_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table residences (id bigint not null, address varchar(255), description varchar(255), name varchar(255), residence_id bigint, manager_id bigint, primary key (id)) engine=InnoDB;
create table roommate_profile (id bigint not null auto_increment, contact_method varchar(255), description varchar(255), drinking integer not null, hobbies varchar(255), pets integer not null, smoking integer not null, user_id bigint not null, primary key (id)) engine=InnoDB;
create table rsvp (id bigint not null auto_increment, event_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table units (id bigint not null, monthly_rent decimal(19,2), unit_description varchar(255), unit_id bigint, unit_number varchar(255), unit_type varchar(255), residence_id bigint, primary key (id)) engine=InnoDB;
create table users (id bigint not null, address varchar(255), college_name varchar(255), date_of_birth date, email varchar(255), fcm varchar(255), first_name varchar(255), img varchar(255), last_name varchar(255), password varchar(255), phone_number varchar(255), postal_code varchar(255), role integer, student_id varchar(255), primary key (id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table roommate_profile add constraint UK_4apvk7j5x1e71vrap7ldeno0v unique (user_id);
alter table leases add constraint FK5noeykhrutapru4f8jnx75sm4 foreign key (unit_id) references units (id);
alter table leases add constraint FKvpstuvbfjau91d62sor5a321 foreign key (user_id) references users (id);
alter table maintenance_requests add constraint FKg0yit7sqjjsyy3vftm7tkkhq3 foreign key (unit_id) references units (id);
alter table maintenance_requests add constraint FKo9pxh9quq4cihxotf6qyw9gpd foreign key (user_id) references users (id);
alter table residences add constraint FKi4u7wp3anfvtl9moqurlncur7 foreign key (manager_id) references users (id);
alter table roommate_profile add constraint FKcruip685m7g5ow3ukirl3uerc foreign key (user_id) references users (id);
alter table rsvp add constraint FK1w4gusckkqul6iyf6r0teov88 foreign key (event_id) references events (id);
alter table rsvp add constraint FKku8yxwk1j6g9muxm7c2f1dmwv foreign key (user_id) references users (id);
alter table units add constraint FK70p695jgs0dhdv5ldf5i1puta foreign key (residence_id) references residences (id);
create table chat_messages (id bigint not null auto_increment, content varchar(255), content_type varchar(255), date datetime(6), sender_id varchar(255), sender_name varchar(255), primary key (id)) engine=InnoDB;
create table events (id bigint not null auto_increment, capacity integer, event_banner varchar(255), event_date_time varchar(255), event_details varchar(255), event_location varchar(255), event_name varchar(255), event_status integer, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table leases (id bigint not null, lease_end_date date, lease_id bigint, lease_length integer, lease_start_date date, lease_status varchar(255), unit_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table maintenance_requests (id bigint not null, img varchar(255), request_date date, request_description varchar(255), request_id bigint, request_status varchar(255), unit_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table residences (id bigint not null, address varchar(255), description varchar(255), name varchar(255), residence_id bigint, manager_id bigint, primary key (id)) engine=InnoDB;
create table roommate_profile (id bigint not null auto_increment, contact_method varchar(255), description varchar(255), drinking integer not null, hobbies varchar(255), pets integer not null, smoking integer not null, user_id bigint not null, primary key (id)) engine=InnoDB;
create table rsvp (id bigint not null auto_increment, event_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table units (id bigint not null, monthly_rent decimal(19,2), unit_description varchar(255), unit_id bigint, unit_number varchar(255), unit_type varchar(255), residence_id bigint, primary key (id)) engine=InnoDB;
create table users (id bigint not null, address varchar(255), college_name varchar(255), date_of_birth date, email varchar(255), fcm varchar(255), first_name varchar(255), img varchar(255), last_name varchar(255), password varchar(255), phone_number varchar(255), postal_code varchar(255), role integer, student_id varchar(255), primary key (id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table roommate_profile add constraint UK_4apvk7j5x1e71vrap7ldeno0v unique (user_id);
alter table leases add constraint FK5noeykhrutapru4f8jnx75sm4 foreign key (unit_id) references units (id);
alter table leases add constraint FKvpstuvbfjau91d62sor5a321 foreign key (user_id) references users (id);
alter table maintenance_requests add constraint FKg0yit7sqjjsyy3vftm7tkkhq3 foreign key (unit_id) references units (id);
alter table maintenance_requests add constraint FKo9pxh9quq4cihxotf6qyw9gpd foreign key (user_id) references users (id);
alter table residences add constraint FKi4u7wp3anfvtl9moqurlncur7 foreign key (manager_id) references users (id);
alter table roommate_profile add constraint FKcruip685m7g5ow3ukirl3uerc foreign key (user_id) references users (id);
alter table rsvp add constraint FK1w4gusckkqul6iyf6r0teov88 foreign key (event_id) references events (id);
alter table rsvp add constraint FKku8yxwk1j6g9muxm7c2f1dmwv foreign key (user_id) references users (id);
alter table units add constraint FK70p695jgs0dhdv5ldf5i1puta foreign key (residence_id) references residences (id);
create table chat_messages (id bigint not null auto_increment, content varchar(255), content_type varchar(255), date datetime(6), sender_id varchar(255), sender_name varchar(255), primary key (id)) engine=InnoDB;
create table events (id bigint not null auto_increment, capacity integer, event_banner varchar(255), event_date_time varchar(255), event_details varchar(255), event_location varchar(255), event_name varchar(255), event_status integer, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table leases (id bigint not null, lease_end_date date, lease_id bigint, lease_length integer, lease_start_date date, lease_status varchar(255), unit_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table maintenance_requests (id bigint not null, img varchar(255), request_date date, request_description varchar(255), request_id bigint, request_status varchar(255), unit_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table residences (id bigint not null, address varchar(255), description varchar(255), name varchar(255), residence_id bigint, manager_id bigint, primary key (id)) engine=InnoDB;
create table roommate_profile (id bigint not null auto_increment, contact_method varchar(255), description varchar(255), drinking integer not null, hobbies varchar(255), pets integer not null, smoking integer not null, user_id bigint not null, primary key (id)) engine=InnoDB;
create table rsvp (id bigint not null auto_increment, event_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table units (id bigint not null, monthly_rent decimal(19,2), unit_description varchar(255), unit_id bigint, unit_number varchar(255), unit_type varchar(255), residence_id bigint, primary key (id)) engine=InnoDB;
create table users (id bigint not null, address varchar(255), college_name varchar(255), date_of_birth date, email varchar(255), fcm varchar(255), first_name varchar(255), img varchar(255), last_name varchar(255), password varchar(255), phone_number varchar(255), postal_code varchar(255), role integer, student_id varchar(255), primary key (id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table roommate_profile add constraint UK_4apvk7j5x1e71vrap7ldeno0v unique (user_id);
alter table leases add constraint FK5noeykhrutapru4f8jnx75sm4 foreign key (unit_id) references units (id);
alter table leases add constraint FKvpstuvbfjau91d62sor5a321 foreign key (user_id) references users (id);
alter table maintenance_requests add constraint FKg0yit7sqjjsyy3vftm7tkkhq3 foreign key (unit_id) references units (id);
alter table maintenance_requests add constraint FKo9pxh9quq4cihxotf6qyw9gpd foreign key (user_id) references users (id);
alter table residences add constraint FKi4u7wp3anfvtl9moqurlncur7 foreign key (manager_id) references users (id);
alter table roommate_profile add constraint FKcruip685m7g5ow3ukirl3uerc foreign key (user_id) references users (id);
alter table rsvp add constraint FK1w4gusckkqul6iyf6r0teov88 foreign key (event_id) references events (id);
alter table rsvp add constraint FKku8yxwk1j6g9muxm7c2f1dmwv foreign key (user_id) references users (id);
alter table units add constraint FK70p695jgs0dhdv5ldf5i1puta foreign key (residence_id) references residences (id);
